### PR TITLE
Abort execution if any policy has missing Rego builtins

### PR DESCRIPTION
**Pull request by ereslibre**
Fixes:https://github.com/kubewarden/policy-server/issues/86

If any Rego policy refers to an unimplemented builtin, abort the execution of the whole policy-server.

### CODE REVIEW

**Comment by ereslibre** [comment]
I honestly don't have a good idea for testing this... In principle all built-ins should be implemented eventually (despite I think some of them are going to be pretty hard... I'm looking at you `rego.parse_module`, for example).

For testing, there are different strategies (e.g. should we test on the policy-evaluator level?, should we also test the behavior from kwctl and policy-server too? -- e.g. that the execution of both really gets aborted with a retcode other than 0?)

**Comment by ereslibre** [comment]
This is how it looks:

```
~/projects/kubewarden/policy-server abort-if-builtin-missing* » cargo run -- --policies ~/policies.yml
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/policy-server --policies /home/ereslibre/policies.yml`
Sep 24 13:52:28.519  INFO policy_server: policies download download_dir="." policies_count=2 status="init"
Sep 24 13:52:28.519  INFO policy_server: policies download status="done"
Sep 24 13:52:28.519  INFO policy_server: kubernetes poller bootstrap status="init"
Sep 24 13:52:28.519  INFO policy_server: kubernetes poller bootstrap status="done"
Sep 24 13:52:28.519  INFO policy_server::kube_poller: spawning cluster context refresh loop
Sep 24 13:52:28.519  INFO policy_server: worker pool bootstrap status="init"
Sep 24 13:52:28.520  INFO policy_server::worker_pool: spawning worker spawned=1 total=8
Sep 24 13:52:28.520  INFO policy_server::worker_pool: spawning worker spawned=2 total=8
Sep 24 13:52:28.520  INFO policy_server::worker_pool: spawning worker spawned=3 total=8
Sep 24 13:52:28.520  INFO policy_server::worker_pool: spawning worker spawned=4 total=8
Sep 24 13:52:28.520  INFO policy_server::worker_pool: spawning worker spawned=5 total=8
Sep 24 13:52:28.520  INFO policy_server::worker_pool: spawning worker spawned=7 total=8
Sep 24 13:52:28.521  INFO policy_server::worker_pool: spawning worker spawned=8 total=8
Sep 24 13:52:28.521  INFO policy_server::worker_pool: spawning worker spawned=6 total=8
Sep 24 13:53:03.418 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.419 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.424 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.436 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.437 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.441 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.442 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.444 ERROR policy_server::worker_pool: cannot spawn worker error="file:///home/ereslibre/faulty-policy.wasm: Err(Could not instantiate policy: missing Rego builtins: rego.parse_module. Aborting execution.)"
Sep 24 13:53:03.444 ERROR policy_server: could not init one of the workers
```

Errors are a bit repetitive, but I think is fine. I could have otherwise used a channel so we only report one per policy, but honestly I didn't think it was worth the effort. We are reporting the error that matters, whether it happens one per thread I don't think is critical.

**Review by flavio — APPROVED** [review]
LGTM, I think we can go ahead and perform a new release of policy-server.

Replies to your comments:
  * I think the current output is fine, I agree to not go too crazy to remove duplicated messages
  * As for testing, this is something we can test with e2e tests later on

**Comment by ereslibre** [comment]
> I think we can go ahead and perform a new release of policy-server.

I'm taking care of it.

**Pull request merged**
