### PR TITLE
wasi policies

### PR DESCRIPTION
**Pull request by flavio**
Support policies that implement the new WASI protocol.

This policy execution mode is not the best one, but it allows the execution of WASM modules that do not leverage waPC. This is the case of modules built by the official Go compile.

### CODE REVIEW

**Comment by flavio** [comment]
Converted to draft. The e2e tests will fail because it's missing the WASI policy to be used. I need to create a WASI policy and host it on ghcr, however I cannot do that because there's no released version of kwctl that can annotate a policy (see https://github.com/kubewarden/kwctl/pull/518)

**Comment by jvanz** [comment]
It looks fine. Let's wait for the kwctl PR get merge and then we can run it on CI and other machines.

**Comment by flavio** [comment]
Moving back to pending review, I've pushed a test policy that is now used by the e2e tests. IMHO we can merge this PR if everything is green

**Comment by jvanz** [comment]
Everything is green and I can build and run test locally as well. Merging this now...

**Pull request merged**
